name: Deploy webpage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: node20
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build site
        run: |
          npm ci
          npm run build

      - name: Deploy to Cloudflare
        id: deploy
        uses: https://github.com/cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: .
          command: deploy --assets ./dist

      - name: Show the Deployment URL
        run: echo "Deployed to $DEPLOYMENT_URL"
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
